import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {api,type SpatialNote,type NoteStatus} from '../../lib/api';
import {useAccount} from '../auth/AccountContext';
import {useLocale} from '../../lib/i18n';
import LanguageSwitch from '../../components/LanguageSwitch';
import SpatialMap,{noteStatus} from './SpatialMap';
import {NoteDetails} from './NotesDialog';

export default function Admin({onExperience}:{onExperience:()=>void}){
 const {user,logout}=useAccount(),{language}=useLocale(),vi=language==='vi';
 const [notes,setNotes]=useState<SpatialNote[]>([]),[floor,setFloor]=useState<1|2>(1),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[selectedId,setSelectedId]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{try{const result=await api<{notes:SpatialNote[]}>('/notes');setNotes(result.notes);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer);},[refresh]);
 const filtered=notes.filter(n=>n.position.floor===floor&&(status==='all'||n.status===status)&&`${n.concern} ${n.request} ${n.authorName} ${n.authorEmail}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const selected=notes.find(n=>n.id===selectedId&&filtered.includes(n));
 const pick=(note:SpatialNote)=>{setSelectedId(note.id);setFloor(note.position.floor);};
 return <main className="admin-page"><header className="admin-header"><div><span className="admin-brand">DAY ZERO</span><span>{vi?'QUẢN TRỊ KHÔNG GIAN':'WORKSPACE ADMIN'}</span></div><nav><LanguageSwitch/><button className="button secondary" onClick={onExperience}>{vi?'Vào trải nghiệm':'Enter simulator'}</button><button className="button secondary" onClick={logout}>{vi?'Đăng xuất':'Sign out'}</button></nav></header><section className="admin-title"><div><span>{vi?'Chào':'Hello'}, {user.name}</span><h1>{vi?'Lắng nghe từ từng vị trí.':'Feedback, mapped to its location.'}</h1><p>{vi?'Xem bất cập, nguyện vọng và phản hồi ngay trên bản đồ văn phòng.':'Review barriers and requests directly on the office floor plan.'}</p></div><button className="button secondary" onClick={()=>void refresh()} disabled={loading}>{vi?'Tải lại ghi chú':'Refresh notes'}</button></section><div className="admin-stats"><div><strong>{notes.length}</strong><span>{vi?'Tổng ghi chú':'Total notes'}</span></div><div><strong>{notes.filter(n=>n.status==='new').length}</strong><span>{vi?'Chờ xem xét':'Awaiting review'}</span></div><div><strong>{notes.filter(n=>n.status==='approved'||n.status==='reviewing').length}</strong><span>{vi?'Đang chuẩn bị':'In progress'}</span></div><div><strong>{notes.filter(n=>n.status==='resolved').length}</strong><span>{vi?'Đã xử lý':'Resolved'}</span></div></div>
 {error&&<p role="alert" className="notes-error">{error}</p>}<section className="admin-filters"><label>{vi?'Tầng':'Floor'}<select value={floor} onChange={e=>setFloor(Number(e.target.value) as 1|2)}><option value="1">{vi?'Tầng 1 & sân trước':'Floor 1 & courtyard'}</option><option value="2">{vi?'Tầng 2':'Floor 2'}</option></select></label><label>{vi?'Trạng thái':'Status'}<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{vi?'Tất cả':'All statuses'}</option>{(['new','reviewing','approved','declined','resolved'] as const).map(s=><option key={s} value={s}>{noteStatus(s,vi)}</option>)}</select></label><label className="admin-search">{vi?'Tìm ghi chú hoặc người gửi':'Find a note or author'}<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={vi?'Nội dung, nguyện vọng, tên, email…':'Content, request, name, email…'}/></label></section>
 <div className="admin-workspace"><section className="admin-map"><div className="admin-panel-title"><h2>{vi?'Bản đồ ghi nhận':'Feedback map'}</h2><span>{filtered.length} {vi?'ghi chú':'notes'} · 1 {vi?'đơn vị':'unit'} = 1 m</span></div><SpatialMap floor={floor} notes={filtered} selected={selected?.id} onSelect={pick}/><p>{vi?'Bấm dấu đánh số để xem nội dung. Các màu tương ứng với trạng thái xử lý.':'Select a numbered marker to review its note. Colors indicate review status.'}</p><div className="map-legend">{(['new','reviewing','approved','declined','resolved'] as const).map(s=><span key={s} className={`note-status ${s}`}>{noteStatus(s,vi)}</span>)}</div></section><aside className="admin-reviews"><h2>{vi?'Ghi chú tại tầng này':'Notes on this floor'}</h2>{loading&&<p role="status">{vi?'Đang tải ghi chú…':'Loading notes…'}</p>}{!loading&&!filtered.length&&<p>{vi?'Không có ghi chú phù hợp. Thử tầng hoặc bộ lọc khác.':'No matching notes. Try another floor or filter.'}</p>}<div className="notes-list">{filtered.map((n,i)=><button key={n.id} onClick={()=>pick(n)} aria-pressed={selected?.id===n.id}><strong>{i+1}. {n.concern}</strong><small>{n.authorName} · {noteStatus(n.status,vi)}</small></button>)}</div>{selected?<><NoteDetails note={selected}/><ReviewForm key={selected.id} note={selected} onSaved={n=>setNotes(list=>list.map(old=>old.id===n.id?n:old))}/></>:<p className="admin-empty">{vi?'Chọn một dấu trên bản đồ hoặc một ghi chú để bắt đầu đánh giá.':'Select a map marker or note to start a review.'}</p>}</aside></div></main>;
}
function ReviewForm({note,onSaved}:{note:SpatialNote;onSaved:(note:SpatialNote)=>void}){
 const {language}=useLocale(),vi=language==='vi';const [status,setStatus]=useState<Exclude<NoteStatus,'new'>>(note.status==='new'?'reviewing':note.status),[review,setReview]=useState(note.review),[version,setVersion]=useState(note.version),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const result=await api<{note:SpatialNote}>(`/notes/${note.id}`,{method:'PATCH',body:JSON.stringify({status,review,version})});onSaved(result.note);setVersion(result.note.version);setMessage(vi?'Đã lưu đánh giá. Người gửi có thể xem phản hồi.':'Review saved. The author can now read it.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <form className="review-form" onSubmit={submit}><h3>{vi?'Cập nhật đánh giá':'Update review'}</h3>{note.version!==version&&<p role="alert">{vi?'Ghi chú đã thay đổi.':'This note has changed.'} <button type="button" onClick={()=>{setVersion(note.version);setReview(note.review);setStatus(note.status==='new'?'reviewing':note.status);}}>{vi?'Nạp đánh giá mới':'Load latest review'}</button></p>}<label>{vi?'Kết quả xem xét':'Review outcome'}<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}>{(['reviewing','approved','declined','resolved'] as const).map(s=><option key={s} value={s}>{noteStatus(s,vi)}</option>)}</select></label><label>{vi?'Đánh giá và phương án':'Assessment and response'}<textarea required maxLength={2000} value={review} onChange={e=>setReview(e.target.value)}/></label><button className="button primary" disabled={busy||!review.trim()||note.version!==version}>{busy?(vi?'Đang lưu…':'Saving…'):(vi?'Lưu đánh giá':'Save review')}</button>{message&&<p role="status">{message}</p>}</form>;
}
