import {useEffect,useState,type FormEvent} from 'react';
import Dialog from '../../components/Dialog';
import {api,type SpatialNote} from '../../lib/api';
import type {Pose} from '../../types/simulator';
import {floorY} from '../../lib/elevator';
import {useLocale} from '../../lib/i18n';
import SpatialMap,{noteStatus} from './SpatialMap';

export default function NotesDialog({pose,onClose}:{pose:Pose;onClose:()=>void}){
 const {language}=useLocale(),vi=language==='vi';
 const [notes,setNotes]=useState<SpatialNote[]>([]),[tab,setTab]=useState<'new'|'mine'>('new'),[selected,setSelected]=useState<SpatialNote|null>(null),[position,setPosition]=useState({floor:pose.floor??1,x:pose.x,z:pose.z,y:pose.y??floorY(pose.floor??1)}),[concern,setConcern]=useState(''),[request,setRequest]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const refresh=()=>{setLoading(true);setError('');api<{notes:SpatialNote[]}>('/notes').then(r=>{setNotes(r.notes);setSelected(current=>r.notes.find(n=>n.id===current?.id)??null);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(refresh,[]);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const {note}=await api<{note:SpatialNote}>('/notes',{method:'POST',body:JSON.stringify({position,concern,request})});setNotes(list=>[note,...list]);setSelected(note);setConcern('');setRequest('');setTab('mine');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog wide title={vi?'Ghi chú không gian':'Space notes'} subtitle={vi?'Ghi lại bất cập và thay đổi bạn mong muốn tại bất kỳ vị trí nào.':'Mark a barrier and the change you need at any location.'} onClose={()=>{if(!busy)onClose();}}>
   <div className="notes-tabs"><button className="button secondary" aria-pressed={tab==='new'} onClick={()=>setTab('new')}>{vi?'Ghi chú mới':'New note'}</button><button className="button secondary" aria-pressed={tab==='mine'} onClick={()=>setTab('mine')}>{vi?'Ghi chú của tôi':'My notes'} ({notes.length})</button><button className="button secondary" disabled={loading||busy} onClick={refresh}>{vi?'Tải lại':'Refresh'}</button></div>
   {error&&<p role="alert" className="notes-error">{error}</p>}
   {tab==='new'?<form onSubmit={submit} className="note-compose"><div><p>{vi?'Dấu xanh là vị trí ghi chú. Bấm bản đồ hoặc dùng phím mũi tên khi bản đồ có focus để chỉnh điểm.':'The blue marker is your note location. Click the map or focus it and use arrow keys to adjust.'}</p><SpatialMap floor={position.floor} point={position} onPoint={p=>setPosition({...position,...p})}/><p className="note-coordinates">{vi?'Tầng':'Floor'} {position.floor} · X {position.x.toFixed(2)} m · Z {position.z.toFixed(2)} m · {vi?'Cao độ':'Height'} {position.y.toFixed(2)} m</p></div><div className="note-fields"><label>{vi?'Bất cập bạn gặp':'Barrier or difficulty'}<textarea required maxLength={2000} value={concern} onChange={e=>setConcern(e.target.value)} placeholder={vi?'Ví dụ: khoảng trống này khó quay xe…':'Example: this space is difficult to turn in…'}/></label><label>{vi?'Nguyện vọng thay đổi':'Requested change'}<textarea required maxLength={2000} value={request} onChange={e=>setRequest(e.target.value)} placeholder={vi?'Bạn mong quản lý thay đổi hoặc hỗ trợ điều gì?':'What change or support would help you?'}/></label><p>{vi?'Quản lý sẽ thấy ghi chú cùng tên của bạn, tầng và vị trí đánh dấu.':'Managers will see your note, your name, floor and marked location.'}</p><button className="button primary" disabled={busy||!concern.trim()||!request.trim()}>{busy?(vi?'Đang gửi…':'Sending…'):(vi?'Gửi ghi chú cho quản lý':'Send note to managers')}</button></div></form>:<div className="note-compose"><div><SpatialMap floor={selected?.position.floor??position.floor} notes={notes} selected={selected?.id} onSelect={setSelected}/><div className="notes-list">{loading&&<p role="status">{vi?'Đang tải…':'Loading…'}</p>}{!loading&&!notes.length&&<p>{vi?'Bạn chưa gửi ghi chú nào.':'You have no notes yet.'}</p>}{notes.map(n=><button key={n.id} onClick={()=>setSelected(n)} aria-pressed={n.id===selected?.id}><strong>{n.concern}</strong><small>{vi?'Tầng':'Floor'} {n.position.floor} · {noteStatus(n.status,vi)}</small></button>)}</div></div><div>{selected?<NoteDetails note={selected}/>:<p>{vi?'Chọn ghi chú để xem phản hồi của quản lý.':'Select a note to see the manager response.'}</p>}</div></div>}
 </Dialog>;
}
export function NoteDetails({note}:{note:SpatialNote}){
 const {language}=useLocale(),vi=language==='vi';
 return <article className="note-details"><span className={`note-status ${note.status}`}>{noteStatus(note.status,vi)}</span><h3>{vi?'Bất cập':'Barrier'}</h3><p>{note.concern}</p><h3>{vi?'Nguyện vọng thay đổi':'Requested change'}</h3><p>{note.request}</p><div className="note-coordinates">{vi?'Tầng':'Floor'} {note.position.floor} · X {note.position.x.toFixed(2)} · Z {note.position.z.toFixed(2)} · Y {note.position.y.toFixed(2)} m<br/>{note.authorName} · {new Date(note.createdAt).toLocaleString(vi?'vi-VN':'en-US')}</div><h3>{vi?'Đánh giá của quản lý':'Manager review'}</h3><p>{note.review||(vi?'Đang chờ quản lý xem xét.':'Awaiting manager review.')}</p>{note.reviewerName&&<small>{note.reviewerName} · {new Date(note.updatedAt).toLocaleString(vi?'vi-VN':'en-US')}</small>}</article>;
}
